apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-externalsecret
  namespace: backend

spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
  - secretKey: db_user
    remoteRef:
      key: app-prod/database
      property: db_user

  - secretKey: db_password
    remoteRef:
      key: app-prod/database
      property: db_password
