apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - backend-svc.yaml
  - configmap.yaml
  - default-policy.yaml
  - deployment.yaml
  - full-policy.yaml
  - hpa.yaml
  - serviceaccount.yaml
