apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: 'git@github.com:YassineDerouich/projet_cloud_security.git'
    targetRevision: main
    path: cloud_native_devops/database/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
