apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - frontend-svc.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - default-policy.yaml
  - full-policy.yaml
  - frontend-analysis.yaml
