apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: database
data:
  01-init.sql: |
    CREATE TABLE IF NOT EXISTS products (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        description TEXT,
        price DECIMAL(10, 2) NOT NULL,
        stock INTEGER DEFAULT 0
    );

    INSERT INTO products (name, description, price, stock) VALUES 
    ('T-Shirt Kubernetes', 'Le vêtement officiel des administrateurs.', 25.99, 100),
    ('Mug HashiCorp Vault', 'Pour garder vos secrets au chaud.', 15.50, 50),
    ('Sticker DevSecOps', 'Fait fuir les hackers.', 2.99, 500);
