apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-secrets
  namespace: database
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: database-secrets
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: app-prod/database
      property: db_user
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: app-prod/database
      property: db_password
