apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-clustersecretstore

spec:
  provider:
    vault:
      server: "https://192.168.1.168:8200"
      path: "secret"
      version: "v2"

      caProvider:
        type: "Secret"
        name: "vault-ca-cert"
        key: "ca.crt"
        namespace: "security"

      auth:
        appRole:
          path: "approle"
          roleRef:
              name: "vault-approlesecret"
              namespace: "security"
              key: "roleId"
          secretRef:
              name: "vault-approlesecret"
              namespace: "security"
              key: "secretId"
